### ISSUE TITLE
Consider adding GO15VENDOREXPERIMENT support

### ISSUE THREAD

**Issue by kardianos** [mattn/gom#51]
In 1.5 the go command will read the environment variable GO15VENDOREXPERIMENT. If enabled, it will use the local "/vendor/" folder for dependencies.

Will you consider supporting this approach?

**Comment by mattn** [comment]
Hmm, thought simplify, removing `src` of path element is enoguh to do.

**Comment by jbrodriguez** [comment]
Hi @mattn have you given any further thoughts to this ?

**Comment by mattn** [comment]
Closing by #57
