### ISSUE TITLE
failed dependent package installation

### ISSUE THREAD

**Issue by syama666** [mattn/gom#64]
`gom install` した時に依存関係のあるパッケージがインストールされずにエラーになる場合があります。
Gomfileの記載は以下のとおりです。
```
gom 'github.com/aws/aws-sdk-go/service/sqs', :commit => 'a28ecdc9741b7905b5198059c94aed20868ffc08'
```
Error message
```
../../aws/credentials/shared_credentials_provider.go:8:2: cannot find package "github.com/vaughan0/go-ini" in any of:
```

12/1のコミット(https://github.com/mattn/gom/commit/3bd65443f0b7423fd6af99b6e7d1f3ea605e2719) 以降に発生しているように思われます。

**Comment by mattn** [comment]
Gomfile を見せてもらってよいでしょうか？

**Comment by mattn** [comment]
修正しました。

**Comment by syama666** [comment]
ありがとうございます
