### ISSUE TITLE
gom install failed for mgo

### ISSUE THREAD

**Issue by kenji4569** [mattn/gom#68]
For the recent commits around Dec1 or Dec 2, 2015, I got the following error on gom install:

```
# gopkg.in/mgo.v2/internal/sasl
internal/sasl/sasl.go:15:24: fatal error: sasl/sasl.h: No such file or directory
 // #include <sasl/sasl.h>
                        ^
```

when running a Dockerfile from golang:1.5.1 (from buildpack-deps:jessie-scm).

I could have installed it on the revsion 78a909167da6e3b7ea010766e09738d086427f6d

Thanks.

**Comment by mattn** [comment]
I guess last change should fix this.

**Comment by kenji4569** [comment]
Thanks, I succeeded for the latest revision!
