### ISSUE TITLE
Go 1.6 and vendor folder renaming

### ISSUE THREAD

**Issue by gnufied** [mattn/gom#78]
Something changed between go versions and that is causing package dependencies to be installed in `vendor` folder rather than usual `_vendor` folder.

This only happens when `gom` is run from custom location. For example:

```
export GOPATH=$(pwd -L)
export PATH=$GOPATH/bin:$PATH
go get github.com/mattn/gom
gom install #will install dependencies in vendor folder while using golang 1.6
```

I usually use above pattern for self-contained project specific `Makefile`. This problem does not happen when I run `gom install` from globally configured `GOPATH`.

**Comment by mattn** [comment]
Sorry I'm not sure which you want. Do you mean _vendor is prefer than vendor? If you prefer _vendor on go16, set GO15VENDOREXPERIMENT=0.
