### ISSUE TITLE
Can not detect go version

### ISSUE THREAD

**Issue by lezi1022** [mattn/gom#82]
root@ubuntu-14:/opt/morningstar/src/github.com/mattn/gom# go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

root@ubuntu-14:/opt/morningstar/src/github.com/mattn/gom# gom
panic: Can not detect go version

goroutine 1 [running]:
github_com_mattn_gover.Version
	/opt/morningstar/src/github.com/mattn/gover/ver.go:21
main.checkVendoringSupport
	/opt/morningstar/src/github.com/mattn/gom/main.go:63
main.$init0
	/opt/morningstar/src/github.com/mattn/gom/main.go:46

goroutine 3 [syscall]:
	goroutine in C code; stack unavailable

**Comment by mattn** [comment]
what `go version` you get?

**Comment by mattn** [comment]
please try to upgrade gom.

**Comment by lezi1022** [comment]
my go version is  "go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64", and upgrade to the lastest gom still not work

**Comment by mattn** [comment]
Yes, already fixed https://github.com/mattn/gover, so you need to do `go get -u github.com/mattn/gom`.
